# Generated by Django 5.1 on 2024-12-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_actor_category_director_screenwriter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie_images/default.jpg', upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(default='defo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='iframe_url',
            field=models.TextField(default='<iframe></iframe>'),
        ),
    ]
