# Generated by Django 5.1 on 2025-01-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_country_productioncompany_movie_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='films.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='movies', to='films.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='films.productioncompany'),
        ),
    ]
